
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEnonassocNEGNUMNEGNEGWYKrightPOWERDIVIDE EQUALS LPAREN MINUS NUMBER PLUS POWER RPAREN TIMESstatement : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression POWER wyk\n                  | expression DIVIDE expressionexpression : MINUS NUMBER %prec NEGNUMexpression : LPAREN expression RPARENexpression : MINUS  LPAREN expression RPAREN  %prec NEGexpression : LPAREN NUMBER RPARENexpression : NUMBERwyk : wyk PLUS wyk\n           | wyk MINUS wyk\n           | wyk TIMES wyk\n           | wyk DIVIDE wykwyk : MINUS NUMBER %prec NEGWYKwyk : MINUS wyk %prec NEGwyk : LPAREN wyk RPARENwyk : NUMBER'
    
_lr_action_items = {'MINUS':([0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[3,7,-11,3,3,3,3,19,3,-7,3,7,-11,-2,-3,-4,-5,19,-19,19,-6,7,-8,-10,19,19,19,19,-16,-17,27,-9,-12,-13,-14,-15,-18,]),'LPAREN':([0,3,5,6,7,8,9,10,12,19,21,26,27,28,29,],[5,12,5,5,5,5,21,5,5,21,21,21,21,21,21,]),'NUMBER':([0,3,5,6,7,8,9,10,12,19,21,26,27,28,29,],[4,11,14,4,4,4,20,4,4,30,20,20,20,20,20,]),'$end':([1,2,4,11,15,16,17,18,20,22,24,25,30,31,33,34,35,36,37,38,],[0,-1,-11,-7,-2,-3,-4,-5,-19,-6,-8,-10,-16,-17,-9,-12,-13,-14,-15,-18,]),'PLUS':([2,4,11,13,14,15,16,17,18,20,22,23,24,25,30,31,32,33,34,35,36,37,38,],[6,-11,-7,6,-11,-2,-3,-4,-5,-19,-6,6,-8,-10,-16,-17,26,-9,-12,-13,-14,-15,-18,]),'TIMES':([2,4,11,13,14,15,16,17,18,20,22,23,24,25,30,31,32,33,34,35,36,37,38,],[8,-11,-7,8,-11,8,8,-4,-5,-19,-6,8,-8,-10,-16,-17,28,-9,28,28,-14,-15,-18,]),'POWER':([2,4,11,13,14,15,16,17,18,20,22,23,24,25,30,31,33,34,35,36,37,38,],[9,-11,-7,9,-11,9,9,9,-5,-19,9,9,-8,-10,-16,-17,-9,-12,-13,-14,-15,-18,]),'DIVIDE':([2,4,11,13,14,15,16,17,18,20,22,23,24,25,30,31,32,33,34,35,36,37,38,],[10,-11,-7,10,-11,10,10,-4,-5,-19,-6,10,-8,-10,-16,-17,29,-9,29,29,-14,-15,-18,]),'RPAREN':([4,11,13,14,15,16,17,18,20,22,23,24,25,30,31,32,33,34,35,36,37,38,],[-11,-7,24,25,-2,-3,-4,-5,-19,-6,33,-8,-10,-16,-17,38,-9,-12,-13,-14,-15,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,5,6,7,8,10,12,],[2,13,15,16,17,22,23,]),'wyk':([9,19,21,26,27,28,29,],[18,31,32,34,35,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',80),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','calc.py',88),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','calc.py',89),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','calc.py',90),
  ('expression -> expression POWER wyk','expression',3,'p_expression_binop','calc.py',91),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','calc.py',92),
  ('expression -> MINUS NUMBER','expression',2,'p_expression_uminus','calc.py',114),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calc.py',120),
  ('expression -> MINUS LPAREN expression RPAREN','expression',4,'p_expression_negation','calc.py',125),
  ('expression -> LPAREN NUMBER RPAREN','expression',3,'p_expression_bracket_number','calc.py',130),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc.py',137),
  ('wyk -> wyk PLUS wyk','wyk',3,'p_wyk_binop','calc.py',144),
  ('wyk -> wyk MINUS wyk','wyk',3,'p_wyk_binop','calc.py',145),
  ('wyk -> wyk TIMES wyk','wyk',3,'p_wyk_binop','calc.py',146),
  ('wyk -> wyk DIVIDE wyk','wyk',3,'p_wyk_binop','calc.py',147),
  ('wyk -> MINUS NUMBER','wyk',2,'p_wyk_negwyk','calc.py',161),
  ('wyk -> MINUS wyk','wyk',2,'p_wyk_neg','calc.py',168),
  ('wyk -> LPAREN wyk RPAREN','wyk',3,'p_wyk_group','calc.py',174),
  ('wyk -> NUMBER','wyk',1,'p_wyk_num','calc.py',180),
]
